version: 2
jobs:
  build:
    docker:
      - image: 'alpine'
    steps:
      - run:
          name: Make sure everything is up-to-date
          command: apk update --no-cache
      - run:
          name: Install git
          command: apk add --no-cache git
      - run:
          name: Install ssh
          command: apk add --no-cache openssh
      - checkout
      - run:
          name: Install CF Cli
          command: |
            apk add --no-cache curl
            curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
            mv cf /usr/local/bin
            cf -v
