version: 2
jobs:
  build:
    docker:
      - image: 'alpine'
    steps:
      - run:
          name: Install git
          command: apk add --no-cache git
      - run:
          name: Install ssh
          command: apk add --no-cache ssh
      - checkout
